#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
DIR="$1"
if [ -z "$DIR" ]; then
	DIR="$(./default-birt-directory)"
fi
readarray -d '' FILES < <(find "$DIR"\
 -not -path '*/.*'\
 -not -name '*.xml'\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f -print0)
SEARCH="Copyright (c)"
echo "search for $SEARCH"
echo "file count = ${#FILES[*]}"
for FILE in "${FILES[@]}"; do
	if [ -f "$FILE" ]; then
		if COUNT=$(grep -ci "$SEARCH" "$FILE" 2> find-copyrights.err.log); then
            if (( "$COUNT" > 1 )); then
                echo "$FILE"
            fi
        fi
	else
		echo "not found: $FILE"
	fi
done