#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
DIR="$1"
if [ -z "$DIR" ]; then
    if [ -z "$BIRT" ]; then
        echo "Please define BIRT"
        exit 1
    fi
	DIR="$BIRT"
fi
FILES=$(find "$DIR"\
 -not -path '*/.*'\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f)
SEARCH="Copyright (c)"
echo "search for $SEARCH"
echo "$FILES" | wc -l
for FILE in $FILES; do
	if [ -f "$FILE" ]; then
		grep -l "$SEARCH" "$FILE" 2> find-copyrights.err.log
	else
		echo "not found: $FILE" > find-copyrights.err.log
	fi
done