#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
DIR="$1"
if [ -z "$DIR" ]; then
	if [ -z "$BIRT" ]; then
		echo "Please define BIRT"
		exit 1
	fi
	DIR="$BIRT"
fi
SEARCH="epl-v10.html"
readarray -d '' FILES < <(find "$DIR"\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f\
 -print0)
for FILE in "${FILES[@]}"; do
	# echo "file = $FILE"
	grep -l "$SEARCH" "$FILE" 2> find-licenses.err.log
done
