#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
DIR="$1"
if [ -z "$DIR" ]; then
    DIR="$(./default-birt-directory)"
fi
SEARCH='Eclipse Public License \(Version \|v *\)1\.0'
echo "SEARCH = $SEARCH"
readarray -d '' FILES < <(find "$DIR"\
 -not -path '*/.*'\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f -print0)
echo "file count = ${#FILES[*]}"
for FILE in "${FILES[@]}"; do
    if RESULT=$(grep "$SEARCH" "$FILE"); then
        echo "file = $FILE"
    fi
done