#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
DIR="$1"
if [ -z "$DIR" ]; then
    if [ -z "$BIRT" ]; then
        echo "Please define BIRT"
        exit 1
    fi
	DIR="$BIRT"
fi
SEARCH="Eclipse Public\\\\n\\\\\\nLicense +(Version +|v)1\\.0"
readarray -d '' FILES < <(find "$DIR"\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f -print0)
for FILE in "${FILES[@]}"; do
    if FOUND=$(pcregrep -M --binary-files=without-match "$SEARCH" "$FILE" 2> find-licenses.err.log); then
        echo "file - $FILE : $FOUND"
    fi
done
# Eclipse  License v1.0
# Eclipse private License v1.0
# - data/org.eclipse.birt.core.script.function/src/org/eclipse/birt/core/script/function/bre/BirtMath.java
# Eclipse Distribution License Version 1.0 ?