#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
DIR="$1"
if [ -z "$DIR" ]; then
	DIR="$BIRT"
fi
echo "searching in $DIR"
FILES=$(find "$DIR"\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f)
SEARCH="Eclipse(\n| )+Public(\n| )+License(\n| )+(Version(\n| )|v)+1.0"
for FILE in $FILES; do
	# echo "file = $FILE"
	pcregrep -l -M "$SEARCH" "$FILE" 2> find-licenses.err.log
done