#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DIR="$1"
if [ -z "$DIR" ]; then
  DIR="$(./default-birt-directory)"
fi
TEST="$2"
FILES=$(find "$DIR" -name "build.properties")
for FILE in $FILES; do
  if [ -z "$TEST" ]; then
    BACKUP_FILE="${FILE}_backup_$TIMESTAMP"
    mv "$FILE" "$BACKUP_FILE"
    sed 's/epl-v10.html/epl-2.0.html/g' "$BACKUP_FILE" > "$FILE"
    rm "$BACKUP_FILE"
  else
    echo "file - $FILE"
    sed 's/epl-v10.html/epl-2.0.html/g' "$FILE"
  fi
done