#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DIR="$1"
if [ -z "$DIR" ]; then
  DIR="$(./default-birt-directory)"
fi
TEST="$2"
# Eclipse Public License - v 1.0
SEARCH='Eclipse Public License \(Version \|v *\|- v *\)1\.0'
COMMAND='s/Eclipse Public License \(Version \|v *\|- v *\)1\.0/Eclipse Public License \12.0/g'
readarray -d '' FILES < <(find "$DIR"\
 -not -path '*/.*'\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f -print0)
for FILE in "${FILES[@]}"; do
  if FOUND=$(grep "$SEARCH" "$FILE"); then
    if [ -z "$TEST" ]; then
      BACKUP_FILE="${FILE}_backup_$TIMESTAMP"
      mv "$FILE" "$BACKUP_FILE"
      sed "$COMMAND" "$BACKUP_FILE" > "$FILE"
      rm "$BACKUP_FILE"
    else
      echo ""
      echo "file - $FILE"
      sed "$COMMAND" "$FILE"
    fi
  fi
done
