#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DIR="$1"
if [ -z "$DIR" ]; then
  DIR="$(./default-birt-directory)"
fi
TEST="$2"
FILES=$(find "$DIR" -name "license.html")
for FILE in $FILES; do
  if [ -z "$TEST" ]; then
    cp epl2/license.html "$FILE"
  else
    echo "$FILE"
  fi
done