#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
TMP_FILE="/tmp/temp_$TIMESTAMP"
NEW_FILE="/tmp/new_$TIMESTAMP"
DIR="$1"
if [ -z "$DIR" ]; then
  if [ -z "$BIRT" ]; then
    echo "Please define BIRT"
    exit 1
  fi
  DIR="$BIRT"
fi
TEST="$2"
SEARCH='Eclipse *\n[ \*]*Public License'
COMMAND='/Eclipse *$/{
  N
  s/Eclipse\(.*\)Public License v1\.0/Eclipse\1Public License v2.0/
}'
readarray -d '' FILES < <(find "$DIR"\
 -not -path '*/.*'\
 -not -name "*.jar"\
 -not -name "*.rptdocument"\
 -not -name "*.class"\
 -not -name "about.html"\
 -not -name "*.png"\
 -not -name "*.zip"\
 -not -name "*.min.js"\
 -not -name "*.svg"\
 -type f -print0)
echo "file count = ${#FILES[*]}"
for FILE in "${FILES[@]}"; do
  cp "$FILE" "$TMP_FILE"
  dos2unix -q "$TMP_FILE"
  if FOUND=$(pcregrep -M "$SEARCH" "$TMP_FILE"); then
    if [ -z "$TEST" ]; then
      sed "$COMMAND" "$TMP_FILE" > "$NEW_FILE"
      if ! diff -q "$FILE" "$TMP_FILE"; then
        unix2dos -q "$NEW_FILE"
      fi
      cp "$NEW_FILE" "$FILE"
    else
      echo ""
      echo "file - $FILE"
      sed "$COMMAND" "$TMP_FILE"
    fi
  fi
  rm "$TMP_FILE"
done
