#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
./upgrade-license-html "$@"
./upgrade-epl-html "$@"
./upgrade-feature-properties "$@"
./upgrade-about-html "$@"
./upgrade-copyright java "$@"
./upgrade-copyright properties "$@"
./upgrade-copyright xml "$@"
./upgrade-build-properties "$@"
# must come after upgrade-copyright
./upgrade-epl-urls "$@"
./upgrade-license-text "$@"
./upgrade-split-license-text "$@"